<?php
/**
 * Robots.txt output, viewer, and analyzer.
 *
 * Generates a production-ready robots.txt via the WordPress `robots_txt`
 * filter. Ensures search engines can fully render pages (JS, CSS, images)
 * while blocking admin areas, spam vectors, and AI training scrapers.
 *
 * @package PerryLabs_SEO
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class PerryLabs_SEO_Robots_Txt {

	/** @var string Transient key for cached robots.txt content. */
	private const CACHE_KEY = 'perrylabs_seo_robots_txt';

	/** @var int Cache TTL in seconds (1 hour). */
	private const CACHE_TTL = 3600;

	/** @var array Known AI training crawlers that can be blocked. */
	private const AI_CRAWLERS = array(
		'GPTBot'           => 'OpenAI (ChatGPT)',
		'ChatGPT-User'     => 'ChatGPT browsing',
		'ClaudeBot'        => 'Anthropic (Claude)',
		'Claude-Web'       => 'Anthropic (Claude web)',
		'Google-Extended'  => 'Google AI (Gemini)',
		'Bytespider'       => 'ByteDance (TikTok)',
		'CCBot'            => 'Common Crawl',
		'FacebookBot'      => 'Meta AI',
		'PerplexityBot'    => 'Perplexity AI',
		'Amazonbot'        => 'Amazon Alexa',
		'cohere-ai'        => 'Cohere',
		'anthropic-ai'     => 'Anthropic (training)',
	);

	public function __construct() {
		// Generate robots.txt output via WordPress filter.
		add_filter( 'robots_txt', array( $this, 'filter_robots_txt' ), 10, 2 );
	}

	/* ──────────────────────────────────────────────────────────────
	 * Robots.txt output
	 * ────────────────────────────────────────────────────────────── */

	/**
	 * Filter the WordPress-generated robots.txt.
	 *
	 * If a custom robots.txt is defined in plugin settings, use that.
	 * Otherwise generate a sensible default.
	 *
	 * @param string $output  The existing robots.txt output.
	 * @param bool   $public  Whether the site is public (blog_public option).
	 * @return string
	 */
	public function filter_robots_txt( string $output, bool $public ): string {
		// If the site is marked non-public, block everything.
		if ( ! $public ) {
			return "User-agent: *\nDisallow: /\n";
		}

		// Check for custom robots.txt in plugin settings.
		$custom = perrylabs_seo_get_option( 'robots_txt_custom', '' );
		if ( ! empty( trim( $custom ) ) ) {
			return $custom;
		}

		// Generate default robots.txt.
		return $this->generate_default();
	}

	/**
	 * Generate the default production robots.txt.
	 *
	 * @return string
	 */
	private function generate_default(): string {
		$sitemap_url = home_url( '/sitemap.xml' );

		$lines = array();

		// Header.
		$lines[] = '# Robots.txt generated by PerryLabs SEO + AEO';
		$lines[] = '# Allow search engines full access for proper rendering.';
		$lines[] = '';

		// Default rules — allow everything except admin/login/spam vectors.
		$lines[] = 'User-agent: *';
		$lines[] = 'Allow: /';
		$lines[] = 'Disallow: /wp-admin/';
		$lines[] = 'Allow: /wp-admin/admin-ajax.php';
		$lines[] = 'Disallow: /wp-login.php';
		$lines[] = 'Disallow: /wp-signup.php';
		$lines[] = 'Disallow: /wp-cron.php';
		$lines[] = 'Disallow: /wp-json/wp/v2/users';
		$lines[] = 'Disallow: /xmlrpc.php';
		$lines[] = 'Disallow: /*?s=';
		$lines[] = 'Disallow: /*&s=';
		$lines[] = '';

		// AI training scrapers.
		$block_ai = perrylabs_seo_get_option( 'robots_block_ai_crawlers', true );

		if ( $block_ai ) {
			/**
			 * Filter the list of AI crawlers to block.
			 *
			 * @param array $crawlers Bot name => label pairs.
			 */
			$crawlers = apply_filters( 'perrylabs_seo_robots_ai_crawlers', self::AI_CRAWLERS );

			if ( ! empty( $crawlers ) ) {
				$lines[] = '# Block AI training scrapers (not search crawlers).';

				foreach ( $crawlers as $bot => $label ) {
					$lines[] = 'User-agent: ' . $bot;
					$lines[] = 'Disallow: /';
					$lines[] = '';
				}
			}
		}

		// Sitemap.
		$lines[] = '# Sitemap';
		$lines[] = 'Sitemap: ' . $sitemap_url;
		$lines[] = '';

		return implode( "\n", $lines );
	}

	/* ──────────────────────────────────────────────────────────────
	 * Fetch & cache (for admin viewer)
	 * ────────────────────────────────────────────────────────────── */

	/**
	 * Fetch the site's robots.txt content.
	 *
	 * @param bool $force_refresh Bypass cache.
	 * @return string|WP_Error
	 */
	public function get_robots_txt( bool $force_refresh = false ) {
		if ( ! $force_refresh ) {
			$cached = get_transient( self::CACHE_KEY );
			if ( false !== $cached ) {
				return $cached;
			}
		}

		$url      = home_url( '/robots.txt' );
		$response = wp_remote_get( $url, array( 'timeout' => 10 ) );

		if ( is_wp_error( $response ) ) {
			return $response;
		}

		$code = wp_remote_retrieve_response_code( $response );
		if ( $code !== 200 ) {
			return new WP_Error(
				'perrylabs_seo_robots_fetch',
				sprintf(
					/* translators: %d: HTTP status code */
					__( 'Could not fetch robots.txt (HTTP %d).', 'perrylabs-seo' ),
					$code
				)
			);
		}

		$body = wp_remote_retrieve_body( $response );
		set_transient( self::CACHE_KEY, $body, self::CACHE_TTL );

		return $body;
	}

	/* ──────────────────────────────────────────────────────────────
	 * Analyzer
	 * ────────────────────────────────────────────────────────────── */

	/**
	 * Analyze robots.txt content and return best-practice recommendations.
	 *
	 * @param string $content The robots.txt content.
	 * @return array Array of ['status' => 'good'|'warning'|'info', 'message' => string].
	 */
	public function analyze( string $content ): array {
		$checks = array();

		// Sitemap reference.
		if ( stripos( $content, 'sitemap:' ) !== false ) {
			$checks[] = array(
				'status'  => 'good',
				'message' => __( 'Sitemap directive found. Search engines can discover your sitemap.', 'perrylabs-seo' ),
			);
		} else {
			$checks[] = array(
				'status'  => 'warning',
				'message' => __( 'No Sitemap directive found. Add "Sitemap: https://yoursite.com/sitemap.xml" to help search engines find your sitemap.', 'perrylabs-seo' ),
			);
		}

		// Check for overly restrictive rules.
		if ( preg_match( '/^User-agent:\s*\*\s*\n\s*Disallow:\s*\/\s*$/mi', $content ) ) {
			$checks[] = array(
				'status'  => 'warning',
				'message' => __( 'A global "Disallow: /" rule was found for all user agents. This blocks all crawling. Make sure this is intentional.', 'perrylabs-seo' ),
			);
		}

		// wp-admin blocking (good practice).
		if ( stripos( $content, 'wp-admin' ) !== false ) {
			$checks[] = array(
				'status'  => 'good',
				'message' => __( 'wp-admin is referenced in robots.txt. Admin areas should generally be blocked from crawling.', 'perrylabs-seo' ),
			);
		}

		// admin-ajax.php allowed (needed for frontend AJAX).
		if ( stripos( $content, 'admin-ajax.php' ) !== false ) {
			$checks[] = array(
				'status'  => 'good',
				'message' => __( 'admin-ajax.php is explicitly allowed. This ensures frontend AJAX functionality is accessible to crawlers.', 'perrylabs-seo' ),
			);
		}

		// AI crawler directives.
		$found_ai = array();

		foreach ( self::AI_CRAWLERS as $bot => $label ) {
			if ( stripos( $content, $bot ) !== false ) {
				$found_ai[] = $label;
			}
		}

		if ( ! empty( $found_ai ) ) {
			$checks[] = array(
				'status'  => 'good',
				'message' => sprintf(
					/* translators: %s: comma-separated list of AI crawler names */
					__( 'AI crawler directives found for: %s', 'perrylabs-seo' ),
					implode( ', ', $found_ai )
				),
			);
		} else {
			$checks[] = array(
				'status'  => 'info',
				'message' => __( 'No AI crawler directives found. Consider adding rules for AI crawlers if you want to control how AI models use your content.', 'perrylabs-seo' ),
			);
		}

		// Crawl-delay.
		if ( stripos( $content, 'crawl-delay' ) !== false ) {
			$checks[] = array(
				'status'  => 'info',
				'message' => __( 'Crawl-delay directive found. Note: Google ignores Crawl-delay. Use Google Search Console to control crawl rate for Googlebot.', 'perrylabs-seo' ),
			);
		}

		return $checks;
	}

	/* ──────────────────────────────────────────────────────────────
	 * Admin tab rendering
	 * ────────────────────────────────────────────────────────────── */

	/**
	 * Render the robots.txt content for the Tools tab.
	 */
	public function render_tab_content(): void {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		$force_refresh = isset( $_GET['refresh'] ) && wp_verify_nonce( $_GET['_wpnonce'] ?? '', 'perrylabs_seo_robots_refresh' );
		$robots_txt    = $this->get_robots_txt( $force_refresh );
		$robots_url    = home_url( '/robots.txt' );
		$refresh_url   = wp_nonce_url(
			admin_url( 'options-general.php?page=perrylabs-seo&tab=tools&refresh=1' ),
			'perrylabs_seo_robots_refresh'
		);
		?>
		<div class="plseo-card">
			<h3><?php esc_html_e( 'Robots.txt', 'perrylabs-seo' ); ?></h3>
			<p class="description">
				<?php esc_html_e( 'The plugin generates a production-ready robots.txt automatically. To override it, enter custom content in the Advanced tab under "Custom Robots.txt".', 'perrylabs-seo' ); ?>
				<a href="https://developers.google.com/search/docs/crawling-indexing/robots/intro" target="_blank" rel="noopener noreferrer"><?php esc_html_e( 'Learn more', 'perrylabs-seo' ); ?> &rarr;</a>
			</p>

			<div style="display: flex; gap: 8px; margin: 12px 0;">
				<a href="<?php echo esc_url( $robots_url ); ?>" target="_blank" rel="noopener noreferrer" class="button">
					<span class="dashicons dashicons-external" style="margin-top: 4px;"></span>
					<?php esc_html_e( 'View Live', 'perrylabs-seo' ); ?>
				</a>
				<a href="<?php echo esc_url( $refresh_url ); ?>" class="button">
					<span class="dashicons dashicons-update" style="margin-top: 4px;"></span>
					<?php esc_html_e( 'Refresh Cache', 'perrylabs-seo' ); ?>
				</a>
			</div>

			<?php if ( is_wp_error( $robots_txt ) ) : ?>
				<div class="notice notice-error inline">
					<p><?php echo esc_html( $robots_txt->get_error_message() ); ?></p>
				</div>
			<?php else : ?>
				<pre style="background: #f6f7f7; padding: 12px; border: 1px solid #dcdcde; overflow-x: auto; white-space: pre-wrap; font-size: 13px; line-height: 1.6; max-height: 300px;"><?php echo esc_html( $robots_txt ); ?></pre>

				<?php $checks = $this->analyze( $robots_txt ); ?>
				<?php if ( ! empty( $checks ) ) : ?>
					<h4 style="margin-top: 16px;"><?php esc_html_e( 'Analysis', 'perrylabs-seo' ); ?></h4>
					<ul style="margin: 0; list-style: none; padding: 0;">
						<?php foreach ( $checks as $check ) : ?>
							<li style="padding: 6px 0; border-bottom: 1px solid #f0f0f1; display: flex; gap: 8px; align-items: flex-start;">
								<?php
								$icon  = 'info';
								$color = '#72aee6';
								if ( 'good' === $check['status'] ) {
									$icon  = 'yes-alt';
									$color = '#00a32a';
								} elseif ( 'warning' === $check['status'] ) {
									$icon  = 'warning';
									$color = '#dba617';
								}
								?>
								<span class="dashicons dashicons-<?php echo esc_attr( $icon ); ?>" style="color: <?php echo esc_attr( $color ); ?>; flex-shrink: 0; margin-top: 2px;"></span>
								<span><?php echo esc_html( $check['message'] ); ?></span>
							</li>
						<?php endforeach; ?>
					</ul>
				<?php endif; ?>
			<?php endif; ?>
		</div>
		<?php
	}
}
